// ─── Events ─────────────────────────────────────────────────────────
export const EVENTS = {
  PLAYER_HEALTH_CHANGED: 'player-health-changed',
  PLAYER_DIED: 'player-died',
  PLAYER_DAMAGE_TAKEN: 'player-damage-taken',
  ENEMY_KILLED: 'enemy-killed',
  ENEMY_HIT: 'enemy-hit',
  XP_CHANGED: 'xp-changed',
  LEVEL_UP: 'level-up',
  WAVE_STARTED: 'wave-started',
  WAVE_CLEARED: 'wave-cleared',
  BOSS_SPAWNED: 'boss-spawned',
  ENHANCEMENT_PICKED: 'enhancement-picked',
  WEAPON_ADDED: 'weapon-added',
  WEAPON_UPGRADED: 'weapon-upgraded',
  ENCHANT_APPLIED: 'enchant-applied',
  ENCHANT_UPGRADED: 'enchant-upgraded',
  GAME_OVER: 'game-over',
  GAME_WON: 'game-won',
  PAUSE_TOGGLE: 'pause-toggle',
  STATS_CHANGED: 'stats-changed',
  CHEST_COLLECTED: 'chest-collected',
  ELITE_KILLED: 'elite-killed',
  CRIT_HIT: 'crit-hit',
  ENCHANT_DAMAGE: 'enchant-damage',
  PLAYER_DASHED: 'player-dashed',
  PLAYER_COUNTER: 'player-counter',
  JOB_CHOSEN: 'job-chosen',
  JOB_SKILL_UPGRADED: 'job-skill-upgraded',
  SWARM_INCOMING: 'swarm-incoming',
  RESET_WEAPON_COOLDOWNS: 'reset-weapon-cooldowns',
  SYNERGY_SKILL_UPGRADE: 'synergy-skill-upgrade',
  PLAYER_DASH_RECHARGE_TICK: 'player_dash_recharge_tick',
} as const;
